// prisma/seed.ts
import { PrismaClient, StepStatus, DatasetType, PreprocStatus, ExperimentStatus, QuantizationType } from "@prisma/client"

const prisma = new PrismaClient()

async function main() {
  console.log("🌱 Seeding database...")

  // ── Roadmap Steps ──────────────────────────────────────────────
  const roadmapData = [
    {
      phase: 1, order: 1, title: "Project Goals & Scope Definition",
      description: "Define the target model specifications, success criteria, and deployment constraints for the Python-focused SLM.",
      status: StepStatus.COMPLETED,
      tasks: [
        { title: "Define model parameter target (300M–500M)", completed: true },
        { title: "Identify target Python libraries for optimization", completed: true },
        { title: "Set hardware deployment constraints (2–4GB RAM)", completed: true },
        { title: "Define evaluation benchmarks (HumanEval, MBPP)", completed: true },
        { title: "Create project documentation structure", completed: true },
      ]
    },
    {
      phase: 2, order: 2, title: "Base Model Selection",
      description: "Research and select the most appropriate base model architecture for fine-tuning, balancing performance with resource constraints.",
      status: StepStatus.COMPLETED,
      tasks: [
        { title: "Evaluate Phi-2 (2.7B) as base candidate", completed: true },
        { title: "Evaluate TinyLlama-1.1B architecture", completed: true },
        { title: "Evaluate CodeGemma-2B capabilities", completed: true },
        { title: "Compare benchmark scores on Python tasks", completed: true },
        { title: "Select final base model: TinyLlama-1.1B", completed: true },
      ]
    },
    {
      phase: 3, order: 3, title: "Dataset Collection",
      description: "Gather high-quality Python code datasets from multiple sources including GitHub, StackOverflow, and curated code repositories.",
      status: StepStatus.IN_PROGRESS,
      tasks: [
        { title: "Collect The Stack v2 Python subset", completed: true },
        { title: "Download CodeSearchNet Python corpus", completed: true },
        { title: "Scrape GitHub trending Python repositories", completed: false },
        { title: "Collect StackOverflow Python Q&A pairs", completed: false },
        { title: "Source Python documentation and tutorials", completed: false },
      ]
    },
    {
      phase: 4, order: 4, title: "Web Scraping Pipeline",
      description: "Build automated scrapers for GitHub repositories, documentation sites, and Python-focused educational resources.",
      status: StepStatus.IN_PROGRESS,
      tasks: [
        { title: "Build GitHub API scraper with rate limiting", completed: true },
        { title: "Create documentation crawler (docs.python.org)", completed: false },
        { title: "Scrape PyPI package documentation", completed: false },
        { title: "Collect Jupyter notebook datasets", completed: false },
        { title: "Pipeline deduplication and URL tracking", completed: false },
      ]
    },
    {
      phase: 5, order: 5, title: "Data Cleaning Pipeline",
      description: "Implement comprehensive data cleaning to remove duplicates, low-quality code, and non-Python content.",
      status: StepStatus.PENDING,
      tasks: [
        { title: "Near-duplicate detection with MinHash LSH", completed: false },
        { title: "Syntax validation with ast.parse()", completed: false },
        { title: "Remove autogenerated and minified code", completed: false },
        { title: "Filter non-English comments and docstrings", completed: false },
        { title: "Quality scoring pipeline implementation", completed: false },
      ]
    },
    {
      phase: 6, order: 6, title: "Dataset Formatting",
      description: "Format cleaned data into instruction-following format suitable for fine-tuning using chat templates.",
      status: StepStatus.PENDING,
      tasks: [
        { title: "Define instruction-following chat template", completed: false },
        { title: "Convert raw code to instruction pairs", completed: false },
        { title: "Format in ShareGPT / Alpaca format", completed: false },
        { title: "Tokenize and compute dataset statistics", completed: false },
        { title: "Split into train/validation/test sets", completed: false },
      ]
    },
    {
      phase: 7, order: 7, title: "Data Augmentation",
      description: "Augment training data with code transformations, variable renaming, and synthetic instruction generation.",
      status: StepStatus.PENDING,
      tasks: [
        { title: "Implement code variable renaming augmentation", completed: false },
        { title: "Generate docstring completion pairs", completed: false },
        { title: "Create function signature completion tasks", completed: false },
        { title: "Synthetic bug-fix pairs generation", completed: false },
        { title: "Library-specific task generation (NumPy, Pandas)", completed: false },
      ]
    },
    {
      phase: 8, order: 8, title: "Training Pipeline",
      description: "Set up full fine-tuning pipeline using QLoRA with efficient gradient checkpointing on target hardware.",
      status: StepStatus.PENDING,
      tasks: [
        { title: "Configure QLoRA training with bitsandbytes", completed: false },
        { title: "Set up PEFT with LoRA adapters", completed: false },
        { title: "Configure gradient checkpointing", completed: false },
        { title: "Implement training monitoring with W&B", completed: false },
        { title: "Run baseline training experiment", completed: false },
      ]
    },
    {
      phase: 9, order: 9, title: "Evaluation & Benchmarking",
      description: "Evaluate model performance on HumanEval, MBPP, and custom Python benchmarks.",
      status: StepStatus.PENDING,
      tasks: [
        { title: "Run HumanEval pass@1 benchmark", completed: false },
        { title: "Run MBPP evaluation suite", completed: false },
        { title: "Custom Python library benchmark (NumPy, Pandas)", completed: false },
        { title: "Latency and memory profiling", completed: false },
        { title: "Comparison against baseline models", completed: false },
      ]
    },
    {
      phase: 10, order: 10, title: "Model Optimization",
      description: "Apply quantization and optimization techniques to reduce model size and improve inference speed.",
      status: StepStatus.PENDING,
      tasks: [
        { title: "Apply GPTQ 4-bit quantization", completed: false },
        { title: "Export to GGUF format for llama.cpp", completed: false },
        { title: "Test AWQ quantization variant", completed: false },
        { title: "Benchmark quantized vs full precision", completed: false },
        { title: "Optimize KV cache settings", completed: false },
      ]
    },
    {
      phase: 11, order: 11, title: "Mobile & Low-Resource Deployment",
      description: "Package model for deployment on devices with 2–4GB RAM using efficient inference runtimes.",
      status: StepStatus.PENDING,
      tasks: [
        { title: "Test llama.cpp deployment on 4GB device", completed: false },
        { title: "Create Ollama model configuration", completed: false },
        { title: "Build FastAPI inference server", completed: false },
        { title: "Create model download and setup scripts", completed: false },
        { title: "Docker containerization", completed: false },
      ]
    },
    {
      phase: 12, order: 12, title: "Final System Architecture",
      description: "Document the complete system, publish model weights, and create comprehensive deployment documentation.",
      status: StepStatus.PENDING,
      tasks: [
        { title: "Publish model to Hugging Face Hub", completed: false },
        { title: "Write comprehensive model card", completed: false },
        { title: "Create inference API documentation", completed: false },
        { title: "Set up public demo endpoint", completed: false },
        { title: "Final benchmarking and release notes", completed: false },
      ]
    },
  ]

  for (const step of roadmapData) {
    const { tasks, ...stepData } = step
    await prisma.roadmapStep.upsert({
      where: { id: `step-${stepData.phase}` },
      update: stepData,
      create: {
        id: `step-${stepData.phase}`,
        ...stepData,
        tasks: { create: tasks }
      }
    })
  }

  // ── Documentation Pages ────────────────────────────────────────
  const docs = [
    {
      id: "doc-1",
      title: "Project Goals & Model Specification",
      slug: "project-goals",
      section: "Overview",
      order: 1,
      tags: ["overview", "goals", "specification"],
      content: `# Project Goals & Model Specification

## Overview

PyCode-SLM is a Python-specialized Small Language Model targeting **300M–500M parameters**, optimized for Python code generation on resource-constrained devices.

## Primary Objectives

- Generate syntactically correct, runnable Python code
- Support major Python ecosystems: NumPy, Pandas, FastAPI, Flask, Django, PyTorch, TensorFlow
- Run efficiently on devices with **2–4GB RAM**
- Achieve competitive HumanEval pass@1 scores

## Model Specifications

| Specification | Target |
|---------------|--------|
| Parameter Count | 300M–500M |
| Quantized Size | < 1GB (4-bit) |
| RAM Requirement | 2–4GB |
| Inference Speed | < 500ms/token on CPU |
| Context Length | 4096 tokens |

## Success Metrics

\`\`\`python
benchmarks = {
    "HumanEval pass@1": ">= 35%",
    "MBPP pass@1": ">= 40%",
    "Custom Python Benchmark": ">= 50%",
    "Inference Speed (4-bit)": "< 500ms/token"
}
\`\`\`

## Target Use Cases

1. **Code Completion** — Complete Python functions from docstrings
2. **Code Generation** — Generate scripts from natural language descriptions
3. **Library Usage** — Demonstrate correct API usage for major libraries
4. **Bug Fixing** — Identify and fix simple Python bugs
5. **Documentation** — Generate docstrings and comments
`
    },
    {
      id: "doc-2",
      title: "Base Model Selection",
      slug: "base-model-selection",
      section: "Architecture",
      order: 2,
      tags: ["architecture", "base-model", "selection"],
      content: `# Base Model Selection

## Candidate Models Evaluated

### TinyLlama-1.1B ✅ Selected

\`\`\`yaml
model: TinyLlama/TinyLlama-1.1B-Chat-v1.0
parameters: 1.1B
architecture: LlamaForCausalLM
context_length: 2048
hidden_size: 2048
num_layers: 22
num_heads: 32
vocab_size: 32000
\`\`\`

**Why Selected:**
- Excellent code performance relative to size
- Strong community support and tooling
- Compatible with QLoRA fine-tuning
- Well-documented architecture

### Phi-2 (Evaluated, Not Selected)

\`\`\`yaml
model: microsoft/phi-2
parameters: 2.7B
context_length: 2048
\`\`\`

Rejected due to: License restrictions, larger footprint than target.

### CodeGemma-2B (Evaluated, Not Selected)

\`\`\`yaml
model: google/codegemma-2b
parameters: 2B
\`\`\`

Rejected due to: Parameter count exceeds deployment target.

## Architecture Details

\`\`\`python
from transformers import AutoModelForCausalLM, AutoTokenizer

model = AutoModelForCausalLM.from_pretrained(
    "TinyLlama/TinyLlama-1.1B-Chat-v1.0",
    torch_dtype=torch.float16,
    device_map="auto"
)
tokenizer = AutoTokenizer.from_pretrained(
    "TinyLlama/TinyLlama-1.1B-Chat-v1.0"
)
\`\`\`
`
    },
    {
      id: "doc-3",
      title: "Dataset Sources & Collection",
      slug: "dataset-sources",
      section: "Data Engineering",
      order: 3,
      tags: ["dataset", "collection", "sources"],
      content: `# Dataset Sources & Collection

## Primary Datasets

### The Stack v2 — Python Subset

\`\`\`python
from datasets import load_dataset

dataset = load_dataset(
    "bigcode/the-stack-v2",
    data_dir="data/python",
    split="train",
    streaming=True
)

# Filter to high-quality Python files
def quality_filter(example):
    return (
        example["lang"] == "Python" and
        example["size"] > 100 and
        example["size"] < 50000 and
        example["alphanum_fraction"] > 0.25
    )

filtered = dataset.filter(quality_filter)
\`\`\`

**Statistics:**
- ~50M Python files
- After filtering: ~8M high-quality files
- Estimated tokens: ~20B

### CodeSearchNet Python

\`\`\`python
dataset = load_dataset("code_search_net", "python")
# ~500K function-docstring pairs
# Excellent for instruction-following fine-tuning
\`\`\`

### StackOverflow Python Q&A

Scraped from Stack Exchange Data Dump:
- ~2M Python questions and accepted answers
- Focus on code-heavy answers
- Filter for >= 10 upvotes

## Dataset Statistics

| Dataset | Samples | Type | Size |
|---------|---------|------|------|
| The Stack v2 Python | 8M | Code | ~40GB |
| CodeSearchNet Python | 500K | Code+Docs | 1.8GB |
| StackOverflow Python | 2M | Q&A | 5GB |
| Python Docs | 50K | Documentation | 200MB |
| GitHub Notebooks | 1M | Notebooks | 8GB |

## Collection Pipeline

\`\`\`python
import asyncio
import aiohttp
from datasets import Dataset

class DatasetCollector:
    def __init__(self, output_dir: str):
        self.output_dir = output_dir
        self.seen_hashes = set()
    
    async def collect_github(self, query: str, max_repos: int = 1000):
        """Collect Python files from GitHub repositories."""
        headers = {"Authorization": f"token {GITHUB_TOKEN}"}
        async with aiohttp.ClientSession(headers=headers) as session:
            repos = await self.search_repos(session, query, max_repos)
            for repo in repos:
                await self.download_python_files(session, repo)
    
    def deduplicate(self, samples: list) -> list:
        """Remove near-duplicates using MinHash LSH."""
        from datasketch import MinHash, MinHashLSH
        lsh = MinHashLSH(threshold=0.85, num_perm=128)
        unique = []
        for i, sample in enumerate(samples):
            mh = self._compute_minhash(sample["content"])
            if not lsh.query(mh):
                lsh.insert(f"s{i}", mh)
                unique.append(sample)
        return unique
\`\`\`
`
    },
    {
      id: "doc-4",
      title: "Web Scraping Pipeline",
      slug: "scraping-pipeline",
      section: "Data Engineering",
      order: 4,
      tags: ["scraping", "pipeline", "github", "stackoverflow"],
      content: `# Web Scraping Pipeline

## Architecture Overview

\`\`\`
GitHub API → Rate Limiter → File Downloader → Quality Filter → Storage
StackOverflow API → Parser → Q&A Extractor → Code Extractor → Storage
Python Docs → Crawler → Parser → Formatter → Storage
\`\`\`

## GitHub Scraper

\`\`\`python
import time
import requests
from pathlib import Path
from typing import Generator

class GitHubScraper:
    BASE_URL = "https://api.github.com"
    RATE_LIMIT = 5000  # requests per hour
    
    def __init__(self, token: str):
        self.session = requests.Session()
        self.session.headers.update({
            "Authorization": f"token {token}",
            "Accept": "application/vnd.github.v3+json"
        })
        self._request_count = 0
        self._window_start = time.time()
    
    def get_python_repos(self, 
                          min_stars: int = 100,
                          page: int = 1) -> list[dict]:
        """Search for Python repositories with quality threshold."""
        params = {
            "q": f"language:python stars:>{min_stars}",
            "sort": "stars",
            "per_page": 100,
            "page": page
        }
        resp = self._rate_limited_get(f"{self.BASE_URL}/search/repositories", params)
        return resp.json()["items"]
    
    def get_file_contents(self, owner: str, repo: str, 
                           path: str) -> str | None:
        """Download file contents with error handling."""
        url = f"{self.BASE_URL}/repos/{owner}/{repo}/contents/{path}"
        resp = self._rate_limited_get(url)
        if resp.status_code == 200:
            import base64
            data = resp.json()
            if data.get("encoding") == "base64":
                return base64.b64decode(data["content"]).decode("utf-8", errors="replace")
        return None
    
    def _rate_limited_get(self, url: str, params: dict = None):
        """Implement token bucket rate limiting."""
        elapsed = time.time() - self._window_start
        if elapsed > 3600:
            self._request_count = 0
            self._window_start = time.time()
        
        if self._request_count >= self.RATE_LIMIT:
            sleep_time = 3600 - elapsed + 60
            time.sleep(sleep_time)
            self._request_count = 0
            self._window_start = time.time()
        
        self._request_count += 1
        return self.session.get(url, params=params)
    
    def scrape_repo_python_files(self, 
                                   owner: str, 
                                   repo: str) -> Generator[dict, None, None]:
        """Yield all Python files from a repository."""
        tree_url = f"{self.BASE_URL}/repos/{owner}/{repo}/git/trees/HEAD"
        resp = self._rate_limited_get(tree_url, {"recursive": "1"})
        
        if resp.status_code != 200:
            return
        
        tree = resp.json().get("tree", [])
        python_files = [f for f in tree if f["path"].endswith(".py")]
        
        for file_info in python_files:
            content = self.get_file_contents(owner, repo, file_info["path"])
            if content and self._is_quality_file(content):
                yield {
                    "path": file_info["path"],
                    "content": content,
                    "repo": f"{owner}/{repo}",
                    "size": file_info["size"]
                }
    
    def _is_quality_file(self, content: str) -> bool:
        """Basic quality heuristics."""
        lines = content.split("\\n")
        return (
            50 < len(lines) < 2000 and
            content.count("def ") > 0 and
            not content.startswith("# AUTO-GENERATED")
        )
\`\`\`

## StackOverflow Scraper

\`\`\`python
import requests
import time

class StackOverflowScraper:
    BASE_URL = "https://api.stackexchange.com/2.3"
    
    def get_python_questions(self, 
                              min_score: int = 5,
                              tagged: str = "python",
                              page: int = 1) -> list[dict]:
        params = {
            "page": page,
            "pagesize": 100,
            "order": "desc",
            "sort": "votes",
            "tagged": tagged,
            "site": "stackoverflow",
            "filter": "withbody",
            "min": min_score,
            "key": STACKEXCHANGE_KEY
        }
        resp = requests.get(f"{self.BASE_URL}/questions", params=params)
        time.sleep(0.1)  # Respectful rate limiting
        return resp.json()["items"]
    
    def extract_code_pairs(self, questions: list[dict]) -> list[dict]:
        """Extract Q&A pairs with Python code blocks."""
        pairs = []
        for q in questions:
            code_blocks = self._extract_code_blocks(q.get("body", ""))
            if code_blocks:
                pairs.append({
                    "question": self._clean_html(q["title"]),
                    "context": self._clean_html(q.get("body", "")),
                    "code": code_blocks[0],
                    "score": q["score"]
                })
        return pairs
\`\`\`
`
    },
    {
      id: "doc-5",
      title: "Data Cleaning Pipeline",
      slug: "data-cleaning",
      section: "Data Engineering",
      order: 5,
      tags: ["cleaning", "deduplication", "quality"],
      content: `# Data Cleaning Pipeline

## Pipeline Stages

\`\`\`
Raw Data → Syntax Validation → Near-Dedup → Quality Scoring → Final Filter
\`\`\`

## Syntax Validation

\`\`\`python
import ast
from typing import Optional

def validate_python_syntax(code: str) -> tuple[bool, Optional[str]]:
    """Validate Python syntax using AST parser."""
    try:
        ast.parse(code)
        return True, None
    except SyntaxError as e:
        return False, str(e)

def batch_validate(samples: list[dict], 
                   code_field: str = "content") -> list[dict]:
    """Filter samples with valid Python syntax."""
    valid = []
    for sample in samples:
        is_valid, error = validate_python_syntax(sample[code_field])
        if is_valid:
            valid.append(sample)
    
    print(f"Validation: {len(valid)}/{len(samples)} samples passed")
    return valid
\`\`\`

## Near-Duplicate Detection

\`\`\`python
from datasketch import MinHash, MinHashLSH
import hashlib

class Deduplicator:
    def __init__(self, threshold: float = 0.85, num_perm: int = 128):
        self.lsh = MinHashLSH(threshold=threshold, num_perm=num_perm)
        self.num_perm = num_perm
        self.seen_exact = set()
    
    def _compute_minhash(self, text: str) -> MinHash:
        """Compute MinHash from text shingles."""
        mh = MinHash(num_perm=self.num_perm)
        shingles = self._get_shingles(text, k=5)
        for shingle in shingles:
            mh.update(shingle.encode("utf-8"))
        return mh
    
    def _get_shingles(self, text: str, k: int = 5) -> set[str]:
        """Get character k-grams from normalized text."""
        text = " ".join(text.split())  # Normalize whitespace
        return {text[i:i+k] for i in range(len(text) - k + 1)}
    
    def deduplicate(self, samples: list[dict]) -> list[dict]:
        """Remove exact and near duplicates."""
        unique = []
        
        for i, sample in enumerate(samples):
            content = sample.get("content", "")
            
            # Exact dedup
            exact_hash = hashlib.md5(content.encode()).hexdigest()
            if exact_hash in self.seen_exact:
                continue
            self.seen_exact.add(exact_hash)
            
            # Near-dedup
            mh = self._compute_minhash(content)
            result = self.lsh.query(mh)
            
            if not result:
                self.lsh.insert(f"s{i}", mh)
                unique.append(sample)
        
        removed = len(samples) - len(unique)
        print(f"Deduplication removed {removed} ({removed/len(samples)*100:.1f}%) duplicates")
        return unique
\`\`\`

## Quality Scoring

\`\`\`python
import re
from dataclasses import dataclass

@dataclass
class QualityScore:
    total: float
    has_docstring: bool
    has_type_hints: bool
    comment_ratio: float
    complexity_score: float
    line_count: int

def compute_quality_score(code: str) -> QualityScore:
    """Multi-dimensional quality scoring for Python code."""
    lines = code.split("\\n")
    non_empty_lines = [l for l in lines if l.strip()]
    
    # Docstring presence
    has_docstring = '"""' in code or "'''" in code
    
    # Type hints
    has_type_hints = "->" in code or ": int" in code or ": str" in code
    
    # Comment ratio
    comment_lines = sum(1 for l in non_empty_lines if l.strip().startswith("#"))
    comment_ratio = comment_lines / max(len(non_empty_lines), 1)
    
    # Structural complexity (functions, classes)
    num_functions = len(re.findall(r"^\\s*def ", code, re.MULTILINE))
    num_classes = len(re.findall(r"^\\s*class ", code, re.MULTILINE))
    complexity_score = min(1.0, (num_functions + num_classes * 2) / 20)
    
    # Compute weighted total
    total = (
        (0.3 if has_docstring else 0) +
        (0.2 if has_type_hints else 0) +
        min(0.2, comment_ratio * 2) +
        complexity_score * 0.3
    )
    
    return QualityScore(
        total=total,
        has_docstring=has_docstring,
        has_type_hints=has_type_hints,
        comment_ratio=comment_ratio,
        complexity_score=complexity_score,
        line_count=len(lines)
    )
\`\`\`
`
    },
    {
      id: "doc-6",
      title: "Dataset Formatting & Templates",
      slug: "dataset-format",
      section: "Data Engineering",
      order: 6,
      tags: ["formatting", "templates", "instruction-tuning"],
      content: `# Dataset Formatting & Instruction Templates

## Instruction Format

We use the ChatML format compatible with TinyLlama's chat template:

\`\`\`
<|system|>
You are a Python programming assistant specialized in writing clean, efficient Python code.
</s>
<|user|>
{instruction}
</s>
<|assistant|>
{response}
</s>
\`\`\`

## Instruction Templates

\`\`\`python
TEMPLATES = {
    "completion": [
        "Complete the following Python function:\\n\\n{code_prefix}",
        "Implement the Python function based on this docstring:\\n\\n{docstring}",
        "Write the body of this Python function:\\n{signature}",
    ],
    "generation": [
        "Write a Python function that {task_description}",
        "Create a Python script to {task_description}",
        "Implement a Python class that {task_description}",
    ],
    "library_usage": [
        "Show me how to use {library} to {task}",
        "Write Python code using {library} for {task}",
        "Demonstrate {library} usage: {task}",
    ],
    "debugging": [
        "Fix the bug in this Python code:\\n\\n{buggy_code}",
        "What's wrong with this Python code and how to fix it?\\n\\n{code}",
    ],
    "explanation": [
        "Explain what this Python code does:\\n\\n{code}",
        "Add docstrings and comments to this Python code:\\n\\n{code}",
    ]
}

def format_sample(sample: dict, template_type: str) -> dict:
    """Format a raw sample into instruction-following format."""
    import random
    template = random.choice(TEMPLATES[template_type])
    
    instruction = template.format(**sample)
    
    return {
        "messages": [
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": instruction},
            {"role": "assistant", "content": sample["output"]}
        ]
    }
\`\`\`

## Tokenization

\`\`\`python
from transformers import AutoTokenizer
from datasets import Dataset

def tokenize_dataset(dataset: Dataset, 
                     model_name: str = "TinyLlama/TinyLlama-1.1B-Chat-v1.0",
                     max_length: int = 2048) -> Dataset:
    tokenizer = AutoTokenizer.from_pretrained(model_name)
    tokenizer.pad_token = tokenizer.eos_token
    
    def tokenize(examples):
        texts = [
            tokenizer.apply_chat_template(
                msgs, tokenize=False, add_generation_prompt=False
            )
            for msgs in examples["messages"]
        ]
        return tokenizer(
            texts,
            truncation=True,
            max_length=max_length,
            padding="max_length"
        )
    
    return dataset.map(tokenize, batched=True, remove_columns=dataset.column_names)
\`\`\`
`
    },
    {
      id: "doc-7",
      title: "LoRA & QLoRA Fine-Tuning",
      slug: "lora-finetuning",
      section: "Training",
      order: 7,
      tags: ["lora", "qlora", "fine-tuning", "peft"],
      content: `# LoRA & QLoRA Fine-Tuning

## What is LoRA?

Low-Rank Adaptation (LoRA) is a parameter-efficient fine-tuning technique that freezes pre-trained model weights and injects trainable rank decomposition matrices into each layer.

For a weight matrix W ∈ ℝ^(d×k), LoRA decomposes the update as:
\`\`\`
ΔW = B × A
where B ∈ ℝ^(d×r), A ∈ ℝ^(r×k), rank r << min(d,k)
\`\`\`

## QLoRA Configuration

\`\`\`python
from transformers import AutoModelForCausalLM, BitsAndBytesConfig
from peft import LoraConfig, get_peft_model, TaskType
import torch

# 4-bit quantization config
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",        # NormalFloat4 quantization
    bnb_4bit_use_double_quant=True,    # Double quantization for memory
    bnb_4bit_compute_dtype=torch.bfloat16
)

# Load base model with quantization
model = AutoModelForCausalLM.from_pretrained(
    "TinyLlama/TinyLlama-1.1B-Chat-v1.0",
    quantization_config=bnb_config,
    device_map="auto",
    trust_remote_code=True
)

# LoRA Configuration
lora_config = LoraConfig(
    task_type=TaskType.CAUSAL_LM,
    r=64,                    # Rank — higher = more expressive, more params
    lora_alpha=128,          # Scaling factor (typically 2x rank)
    target_modules=[         # Which weight matrices to adapt
        "q_proj",
        "k_proj", 
        "v_proj",
        "o_proj",
        "gate_proj",
        "up_proj",
        "down_proj"
    ],
    lora_dropout=0.05,
    bias="none",
)

model = get_peft_model(model, lora_config)
model.print_trainable_parameters()
# Trainable params: ~40M / 1.1B (3.6%)
\`\`\`

## Training with SFTTrainer

\`\`\`python
from trl import SFTTrainer, SFTConfig
from transformers import TrainingArguments

training_args = SFTConfig(
    output_dir="./checkpoints/pycode-slm-v1",
    num_train_epochs=3,
    per_device_train_batch_size=4,
    gradient_accumulation_steps=4,   # Effective batch = 16
    learning_rate=2e-4,
    lr_scheduler_type="cosine",
    warmup_ratio=0.05,
    fp16=True,
    optim="paged_adamw_32bit",       # Memory-efficient optimizer
    logging_steps=10,
    evaluation_strategy="steps",
    eval_steps=100,
    save_steps=100,
    save_total_limit=3,
    max_seq_length=2048,
    report_to="wandb",
    run_name="pycode-slm-v1-qlora"
)

trainer = SFTTrainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=eval_dataset,
    tokenizer=tokenizer,
)

trainer.train()
\`\`\`

## Hyperparameter Guidelines

| Parameter | Conservative | Recommended | Aggressive |
|-----------|-------------|-------------|-----------|
| LoRA Rank (r) | 16 | 64 | 128 |
| LoRA Alpha | 32 | 128 | 256 |
| Learning Rate | 1e-4 | 2e-4 | 5e-4 |
| Batch Size | 2 | 4 | 8 |
| Epochs | 1 | 3 | 5 |
`
    },
    {
      id: "doc-8",
      title: "Training Pipeline & Infrastructure",
      slug: "training-pipeline",
      section: "Training",
      order: 8,
      tags: ["training", "pipeline", "infrastructure", "gpu"],
      content: `# Training Pipeline & Infrastructure

## Hardware Requirements

| Setup | VRAM | Training Time | Recommended |
|-------|------|---------------|-------------|
| Single A100 80GB | 80GB | ~8 hours | Production |
| Single A100 40GB | 40GB | ~14 hours | Development |
| 2x RTX 3090 | 48GB | ~20 hours | Budget |
| Google Colab A100 | 40GB | Pay-per-use | Prototyping |

## Full Training Script

\`\`\`python
#!/usr/bin/env python3
"""
PyCode-SLM Training Entry Point
"""
import os
import torch
import wandb
from pathlib import Path
from dataclasses import dataclass, field
from transformers import (
    AutoModelForCausalLM,
    AutoTokenizer,
    BitsAndBytesConfig,
    HfArgumentParser
)
from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training
from trl import SFTTrainer, SFTConfig
from datasets import load_from_disk

@dataclass
class ModelArguments:
    base_model: str = field(default="TinyLlama/TinyLlama-1.1B-Chat-v1.0")
    use_4bit: bool = field(default=True)
    use_nested_quant: bool = field(default=True)

@dataclass  
class DataArguments:
    dataset_path: str = field(default="./data/processed")
    max_seq_length: int = field(default=2048)

def setup_model(args: ModelArguments):
    bnb_config = BitsAndBytesConfig(
        load_in_4bit=args.use_4bit,
        bnb_4bit_quant_type="nf4",
        bnb_4bit_use_double_quant=args.use_nested_quant,
        bnb_4bit_compute_dtype=torch.bfloat16
    )
    
    model = AutoModelForCausalLM.from_pretrained(
        args.base_model,
        quantization_config=bnb_config,
        device_map="auto"
    )
    
    model = prepare_model_for_kbit_training(model)
    
    lora_config = LoraConfig(
        r=64, lora_alpha=128, lora_dropout=0.05,
        target_modules=["q_proj","k_proj","v_proj","o_proj",
                        "gate_proj","up_proj","down_proj"],
        bias="none", task_type="CAUSAL_LM"
    )
    
    return get_peft_model(model, lora_config)

def main():
    wandb.init(project="pycode-slm", name="v1-qlora-training")
    
    model_args = ModelArguments()
    data_args = DataArguments()
    
    model = setup_model(model_args)
    tokenizer = AutoTokenizer.from_pretrained(model_args.base_model)
    tokenizer.pad_token = tokenizer.eos_token
    
    dataset = load_from_disk(data_args.dataset_path)
    
    trainer = SFTTrainer(
        model=model,
        tokenizer=tokenizer,
        train_dataset=dataset["train"],
        eval_dataset=dataset["validation"],
        args=SFTConfig(
            output_dir="./checkpoints",
            num_train_epochs=3,
            per_device_train_batch_size=4,
            gradient_accumulation_steps=4,
            learning_rate=2e-4,
            fp16=True,
            report_to="wandb"
        )
    )
    
    trainer.train()
    trainer.save_model("./final-model")

if __name__ == "__main__":
    main()
\`\`\`
`
    },
    {
      id: "doc-9",
      title: "Evaluation & Benchmarking",
      slug: "evaluation",
      section: "Evaluation",
      order: 9,
      tags: ["evaluation", "benchmarks", "humaneval", "mbpp"],
      content: `# Evaluation & Benchmarking

## Benchmarks Used

### HumanEval (OpenAI)

\`\`\`python
from human_eval.data import write_jsonl, read_problems
from human_eval.evaluation import evaluate_functional_correctness

problems = read_problems()

def generate_completions(model, tokenizer, problems: dict) -> list[dict]:
    completions = []
    for task_id, problem in problems.items():
        prompt = problem["prompt"]
        inputs = tokenizer(prompt, return_tensors="pt").to(model.device)
        
        with torch.no_grad():
            outputs = model.generate(
                **inputs,
                max_new_tokens=512,
                temperature=0.2,
                do_sample=True,
                pad_token_id=tokenizer.eos_token_id
            )
        
        completion = tokenizer.decode(outputs[0][inputs["input_ids"].shape[1]:])
        completions.append({
            "task_id": task_id,
            "completion": completion
        })
    
    return completions

# Run evaluation
completions = generate_completions(model, tokenizer, problems)
write_jsonl("completions.jsonl", completions)
results = evaluate_functional_correctness("completions.jsonl")
print(f"pass@1: {results['pass@1']:.3f}")
\`\`\`

### MBPP (Mostly Basic Python Problems)

\`\`\`python
from datasets import load_dataset

mbpp = load_dataset("mbpp", split="test")

def evaluate_mbpp(model, tokenizer) -> dict:
    results = {"passed": 0, "total": len(mbpp)}
    
    for example in mbpp:
        prompt = f"Write a Python function: {example['text']}\\n\\n"
        completion = generate_code(model, tokenizer, prompt)
        
        # Test against provided test cases
        test_code = "\\n".join(example["test_list"])
        passed = run_tests_safely(completion + "\\n" + test_code)
        
        if passed:
            results["passed"] += 1
    
    results["pass@1"] = results["passed"] / results["total"]
    return results
\`\`\`

## Expected Benchmark Targets

| Benchmark | Base TinyLlama | After Fine-tuning | Target |
|-----------|---------------|-------------------|--------|
| HumanEval pass@1 | 8.2% | 32-40% | ≥ 35% |
| MBPP pass@1 | 12.4% | 38-45% | ≥ 40% |
| Custom Python | N/A | 45-55% | ≥ 50% |

## Memory & Latency Profiling

\`\`\`python
import torch
import time
import psutil

def profile_inference(model, tokenizer, prompt: str) -> dict:
    """Profile memory and latency for a single inference."""
    process = psutil.Process()
    
    # Memory before
    mem_before = process.memory_info().rss / 1024**2  # MB
    
    inputs = tokenizer(prompt, return_tensors="pt")
    
    # Warmup
    with torch.no_grad():
        model.generate(**inputs, max_new_tokens=10)
    
    # Timed run
    start = time.perf_counter()
    with torch.no_grad():
        outputs = model.generate(**inputs, max_new_tokens=100)
    elapsed = time.perf_counter() - start
    
    mem_after = process.memory_info().rss / 1024**2
    num_tokens = outputs.shape[1] - inputs["input_ids"].shape[1]
    
    return {
        "total_time_s": elapsed,
        "tokens_per_second": num_tokens / elapsed,
        "memory_mb": mem_after - mem_before,
        "tokens_generated": num_tokens
    }
\`\`\`
`
    },
    {
      id: "doc-10",
      title: "Model Optimization & Quantization",
      slug: "optimization",
      section: "Deployment",
      order: 10,
      tags: ["quantization", "optimization", "gguf", "gptq"],
      content: `# Model Optimization & Quantization

## Quantization Methods Compared

| Method | Size Reduction | Quality Loss | Speed Gain | Use Case |
|--------|---------------|-------------|-----------|---------|
| FP16 | 50% | None | 1.5x | GPU server |
| INT8 | 75% | Minimal | 2x | GPU/edge |
| GPTQ 4-bit | 87.5% | Small | 3x | GPU edge |
| GGUF Q4_K_M | 87.5% | Small | 4x | CPU/mobile |
| GGUF Q5_K_M | 84% | Minimal | 3.5x | CPU balanced |

## GPTQ Quantization

\`\`\`python
from auto_gptq import AutoGPTQForCausalLM, BaseQuantizeConfig

quantize_config = BaseQuantizeConfig(
    bits=4,
    group_size=128,
    desc_act=False,
    sym=True
)

model = AutoGPTQForCausalLM.from_pretrained(
    "./final-model",
    quantize_config
)

# Calibration data
calibration_data = load_calibration_dataset()

model.quantize(calibration_data)
model.save_quantized("./pycode-slm-gptq-4bit")
\`\`\`

## GGUF Conversion (for llama.cpp)

\`\`\`bash
# Install llama.cpp
git clone https://github.com/ggerganov/llama.cpp
cd llama.cpp && make

# Convert to GGUF
python convert_hf_to_gguf.py ./final-model \\
    --outfile pycode-slm.gguf \\
    --outtype f16

# Quantize to Q4_K_M (best quality/size ratio)
./llama-quantize pycode-slm.gguf pycode-slm-Q4_K_M.gguf Q4_K_M

# Test
./llama-cli -m pycode-slm-Q4_K_M.gguf \\
    -p "Write a Python function to sort a list:" \\
    -n 200
\`\`\`

## Ollama Deployment

\`\`\`dockerfile
# Modelfile
FROM ./pycode-slm-Q4_K_M.gguf

PARAMETER temperature 0.2
PARAMETER top_p 0.9
PARAMETER stop "<|user|>"
PARAMETER stop "</s>"
PARAMETER num_ctx 4096

SYSTEM """
You are PyCode-SLM, an expert Python programming assistant.
You write clean, efficient, well-documented Python code.
"""
\`\`\`

\`\`\`bash
ollama create pycode-slm -f Modelfile
ollama run pycode-slm "Write a FastAPI endpoint for user authentication"
\`\`\`
`
    },
    {
      id: "doc-11",
      title: "Mobile & Low-Resource Deployment",
      slug: "mobile-deployment",
      section: "Deployment",
      order: 11,
      tags: ["deployment", "mobile", "inference", "fastapi"],
      content: `# Mobile & Low-Resource Deployment

## Target Deployment Environments

| Environment | RAM | Storage | Runtime |
|-------------|-----|---------|---------|
| Raspberry Pi 5 | 8GB | 32GB | llama.cpp |
| Android (8GB) | 8GB | 16GB | llama.cpp Android |
| Edge Server | 4GB | 16GB | Ollama |
| Docker Container | 2GB | 4GB | FastAPI + llama.cpp |

## FastAPI Inference Server

\`\`\`python
from fastapi import FastAPI, HTTPException
from fastapi.responses import StreamingResponse
from pydantic import BaseModel
from llama_cpp import Llama
import asyncio
import json

app = FastAPI(title="PyCode-SLM API", version="1.0.0")

# Load model once at startup
model = Llama(
    model_path="./pycode-slm-Q4_K_M.gguf",
    n_ctx=4096,
    n_threads=4,
    n_gpu_layers=0,   # CPU-only for edge deployment
    verbose=False
)

class GenerationRequest(BaseModel):
    prompt: str
    max_tokens: int = 512
    temperature: float = 0.2
    top_p: float = 0.9
    stream: bool = False

SYSTEM_PROMPT = "You are PyCode-SLM, an expert Python programming assistant."

def format_prompt(user_prompt: str) -> str:
    return f"<|system|>\\n{SYSTEM_PROMPT}\\n</s>\\n<|user|>\\n{user_prompt}\\n</s>\\n<|assistant|>\\n"

@app.post("/v1/generate")
async def generate(request: GenerationRequest):
    formatted = format_prompt(request.prompt)
    
    if request.stream:
        def generate_stream():
            for chunk in model(formatted, 
                              max_tokens=request.max_tokens,
                              temperature=request.temperature,
                              stream=True):
                token = chunk["choices"][0]["text"]
                yield f"data: {json.dumps({'token': token})}\\n\\n"
            yield "data: [DONE]\\n\\n"
        
        return StreamingResponse(generate_stream(), 
                                 media_type="text/event-stream")
    
    output = model(formatted,
                   max_tokens=request.max_tokens,
                   temperature=request.temperature,
                   top_p=request.top_p,
                   stop=["</s>", "<|user|>"])
    
    return {
        "generated_text": output["choices"][0]["text"],
        "tokens_used": output["usage"]["total_tokens"]
    }

@app.get("/health")
async def health():
    return {"status": "ok", "model": "pycode-slm-Q4_K_M"}
\`\`\`

## Docker Deployment

\`\`\`dockerfile
FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \\
    build-essential \\
    cmake \\
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8000

CMD ["uvicorn", "server:app", "--host", "0.0.0.0", "--port", "8000"]
\`\`\`

\`\`\`yaml
# docker-compose.yml
version: '3.8'
services:
  pycode-slm:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
    environment:
      - MODEL_PATH=/app/models/pycode-slm-Q4_K_M.gguf
    mem_limit: 4g
    restart: unless-stopped
\`\`\`
`
    },
    {
      id: "doc-12",
      title: "Final System Architecture",
      slug: "system-architecture",
      section: "Architecture",
      order: 12,
      tags: ["architecture", "system", "overview"],
      content: `# Final System Architecture

## Complete Pipeline Overview

\`\`\`
Data Sources
├── GitHub API (8M+ Python files)
├── StackOverflow (2M+ Q&A pairs)
├── Python Documentation
└── Jupyter Notebooks

    ↓ Collection Pipeline (async scrapers)

Raw Dataset (~55M samples)

    ↓ Cleaning Pipeline
    ├── Syntax Validation (ast.parse)
    ├── Near-Dedup (MinHash LSH, threshold=0.85)
    ├── Quality Scoring (multi-dimensional)
    └── Language Detection

Cleaned Dataset (~15M samples)

    ↓ Formatting Pipeline
    ├── Instruction Template Generation
    ├── ChatML Format Conversion
    └── Tokenization (TinyLlama tokenizer)

Training Dataset (~10M instruction pairs)

    ↓ QLoRA Fine-tuning
    ├── Base: TinyLlama-1.1B
    ├── LoRA: r=64, alpha=128
    ├── Quantization: 4-bit NF4
    └── Hardware: A100 40GB × 1, ~14h

Fine-tuned Model (LoRA adapters)

    ↓ Merging & Optimization
    ├── Merge LoRA → Base Model
    ├── GPTQ 4-bit Quantization
    └── GGUF Q4_K_M Conversion

Optimized Model (~700MB)

    ↓ Deployment
    ├── Ollama (local desktop)
    ├── FastAPI Server (Docker)
    ├── llama.cpp (edge devices)
    └── Hugging Face Hub (public)
\`\`\`

## Technology Stack Summary

\`\`\`yaml
Data Pipeline:
  - Python 3.11+
  - aiohttp / asyncio
  - datasets (HuggingFace)
  - datasketch (MinHash)
  - pandas / polars

Training:
  - PyTorch 2.x
  - transformers 4.x
  - PEFT (LoRA/QLoRA)
  - trl (SFTTrainer)
  - bitsandbytes
  - Weights & Biases

Inference:
  - llama.cpp
  - FastAPI
  - Ollama
  - Docker

Evaluation:
  - human_eval (OpenAI)
  - MBPP benchmark
  - Custom test suite
\`\`\`

## Model Card

\`\`\`markdown
# PyCode-SLM v1.0

**Model:** PyCode-SLM-300M-Python  
**Base:** TinyLlama-1.1B-Chat-v1.0  
**Fine-tuned on:** 10M Python instruction pairs  
**Quantization:** GGUF Q4_K_M  
**Size:** ~700MB  

**Benchmarks:**
- HumanEval pass@1: 37.2%
- MBPP pass@1: 42.1%

**Usage:**
ollama run pycode-slm "Write a FastAPI CRUD API"
\`\`\`
`
    },
  ]

  for (const doc of docs) {
    await prisma.documentationPage.upsert({
      where: { slug: doc.slug },
      update: { title: doc.title, content: doc.content, section: doc.section, tags: doc.tags },
      create: doc
    })
  }

  // ── Datasets ───────────────────────────────────────────────────
  await prisma.dataset.createMany({
    skipDuplicates: true,
    data: [
      {
        id: "ds-1",
        name: "The Stack v2 — Python",
        description: "Deduplicated Python source code from GitHub. The largest publicly available code dataset.",
        sourceUrl: "https://huggingface.co/datasets/bigcode/the-stack-v2",
        datasetType: DatasetType.CODE,
        numSamples: 8000000,
        sizeBytes: BigInt(40 * 1024 * 1024 * 1024),
        preprocessStatus: PreprocStatus.CLEANED,
        tags: ["Python", "GitHub", "Code"],
        format: "parquet",
        license: "various"
      },
      {
        id: "ds-2",
        name: "CodeSearchNet Python",
        description: "Function-docstring pairs from open source Python repos.",
        sourceUrl: "https://huggingface.co/datasets/code_search_net",
        datasetType: DatasetType.CODE,
        numSamples: 503502,
        sizeBytes: BigInt(1800 * 1024 * 1024),
        preprocessStatus: PreprocStatus.FORMATTED,
        tags: ["Python", "Functions", "Docstrings"],
        format: "jsonl",
        license: "MIT"
      },
      {
        id: "ds-3",
        name: "StackOverflow Python Q&A",
        description: "High-quality Python questions and answers from StackOverflow data dump.",
        sourceUrl: "https://archive.org/details/stackexchange",
        datasetType: DatasetType.QA,
        numSamples: 2100000,
        sizeBytes: BigInt(5 * 1024 * 1024 * 1024),
        preprocessStatus: PreprocStatus.CLEANING,
        tags: ["Python", "Q&A", "StackOverflow"],
        format: "xml/jsonl",
        license: "CC-BY-SA 4.0"
      },
      {
        id: "ds-4",
        name: "Python Docs Corpus",
        description: "Official Python documentation, tutorials, and library reference docs.",
        sourceUrl: "https://docs.python.org",
        datasetType: DatasetType.TEXT,
        numSamples: 52000,
        sizeBytes: BigInt(200 * 1024 * 1024),
        preprocessStatus: PreprocStatus.FORMATTED,
        tags: ["Python", "Documentation", "Official"],
        format: "markdown",
        license: "Python PSF"
      },
      {
        id: "ds-5",
        name: "GitHub Jupyter Notebooks",
        description: "Python Jupyter notebooks from trending GitHub repositories.",
        sourceUrl: "https://github.com/trending/python",
        datasetType: DatasetType.CODE,
        numSamples: 1000000,
        sizeBytes: BigInt(8 * 1024 * 1024 * 1024),
        preprocessStatus: PreprocStatus.RAW,
        tags: ["Python", "Jupyter", "Notebooks", "Data Science"],
        format: "ipynb",
        license: "various"
      },
    ]
  })

  // ── Experiments ────────────────────────────────────────────────
  const exp1 = await prisma.experiment.upsert({
    where: { id: "exp-1" },
    update: {},
    create: {
      id: "exp-1",
      name: "Baseline QLoRA — TinyLlama",
      description: "Initial fine-tuning run to establish baseline metrics.",
      baseModel: "TinyLlama/TinyLlama-1.1B-Chat-v1.0",
      datasetId: "ds-2",
      status: ExperimentStatus.COMPLETED,
      loraRank: 16,
      loraAlpha: 32,
      batchSize: 4,
      learningRate: 2e-4,
      epochs: 1,
      evalLoss: 1.42,
      evalAccuracy: 0.71,
      pass1Score: 0.18,
      config: {
        quantization: "4bit",
        optimizer: "paged_adamw_32bit",
        gradient_checkpointing: true,
        max_seq_length: 1024
      }
    }
  })

  const exp2 = await prisma.experiment.upsert({
    where: { id: "exp-2" },
    update: {},
    create: {
      id: "exp-2",
      name: "QLoRA r=64 — Extended Dataset",
      description: "Higher rank LoRA with expanded dataset including The Stack v2.",
      baseModel: "TinyLlama/TinyLlama-1.1B-Chat-v1.0",
      datasetId: "ds-1",
      status: ExperimentStatus.COMPLETED,
      loraRank: 64,
      loraAlpha: 128,
      batchSize: 4,
      learningRate: 2e-4,
      epochs: 3,
      evalLoss: 0.98,
      evalAccuracy: 0.84,
      pass1Score: 0.312,
      bleuScore: 0.421,
      config: {
        quantization: "4bit_nf4",
        optimizer: "paged_adamw_32bit",
        gradient_checkpointing: true,
        max_seq_length: 2048,
        warmup_ratio: 0.05
      }
    }
  })

  // Add experiment logs
  const logData = []
  for (let step = 0; step <= 500; step += 10) {
    logData.push({
      experimentId: "exp-2",
      step,
      loss: 2.1 * Math.exp(-step / 200) + 0.9 + (Math.random() * 0.1 - 0.05),
      learningRate: 2e-4,
    })
  }
  await prisma.experimentLog.createMany({ data: logData, skipDuplicates: true })

  // ── Model Versions ─────────────────────────────────────────────
  await prisma.modelVersion.createMany({
    skipDuplicates: true,
    data: [
      {
        id: "mv-1",
        name: "PyCode-SLM",
        version: "v0.1-baseline",
        description: "Initial baseline model from first training run.",
        parameterCount: BigInt(1100000000),
        experimentId: "exp-1",
        quantization: QuantizationType.NONE,
        deploymentFormat: "safetensors",
        pass1Score: 0.18,
        fileSizeBytes: BigInt(2200 * 1024 * 1024),
        isDeployed: false,
      },
      {
        id: "mv-2",
        name: "PyCode-SLM",
        version: "v0.2-qlora64",
        description: "Improved model with r=64 LoRA and 3 epochs training.",
        parameterCount: BigInt(1100000000),
        experimentId: "exp-2",
        quantization: QuantizationType.NONE,
        deploymentFormat: "safetensors",
        pass1Score: 0.312,
        bleuScore: 0.421,
        fileSizeBytes: BigInt(2200 * 1024 * 1024),
        isDeployed: false,
      },
      {
        id: "mv-3",
        name: "PyCode-SLM",
        version: "v0.2-qlora64-gptq4",
        description: "GPTQ 4-bit quantized version for edge deployment.",
        parameterCount: BigInt(1100000000),
        experimentId: "exp-2",
        quantization: QuantizationType.GPTQ,
        deploymentFormat: "gptq",
        pass1Score: 0.298,
        bleuScore: 0.415,
        fileSizeBytes: BigInt(700 * 1024 * 1024),
        isDeployed: true,
        notes: "Active deployment. Running on edge inference server."
      },
    ]
  })

  // ── Notes ──────────────────────────────────────────────────────
  await prisma.note.createMany({
    skipDuplicates: true,
    data: [
      {
        id: "note-1",
        title: "Training Observations — Run 2",
        content: `# Training Run 2 Notes

## Key Observations

The loss curve shows a significant improvement with r=64 vs r=16 LoRA rank.

\`\`\`
Epoch 1: loss=1.82 → eval_loss=1.31
Epoch 2: loss=1.21 → eval_loss=1.05
Epoch 3: loss=0.99 → eval_loss=0.98
\`\`\`

## Issues Encountered

- GPU OOM at batch_size=8, reduced to 4 with grad_accum=4
- Learning rate warmup critical — removed it in first run (mistake)

## Next Steps

- Try DPO alignment on preference data
- Experiment with longer context (4096 tokens)
- Test LoRA rank 128
`,
        tags: ["training", "observations", "qlora"],
        pinned: true
      },
      {
        id: "note-2",
        title: "Dataset Quality Issues",
        content: `# Dataset Quality Issues Log

## Problems Found

1. **The Stack v2** contains ~15% auto-generated code (migrations, proto files)
2. StackOverflow has many outdated Python 2 code samples
3. Some GitHub repos have binary files mistakenly included

## Solutions Applied

- Added file path filter: skip \`*_pb2.py\`, \`*migrations*\`, \`*.min.py\`
- Added Python 2 detection heuristic: \`print "x"\` pattern → filter
- Binary detection: skip files with >5% non-printable characters
`,
        tags: ["dataset", "quality", "issues"],
        pinned: false
      },
    ]
  })

  console.log("✅ Seed complete!")
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect())
